#!/usr/bin/env python3
"""
Plot memory utilization metrics from MGPUSim SQLite database.

Usage:
    python plot_memory_utilization.py <database_file.sqlite3>

Example:
    python plot_memory_utilization.py akita_sim_12345.sqlite3

The database is generated by running simulations with -timing -report-all flags.
"""

import sqlite3
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path


def load_metrics(db_path):
    """Load metrics from the SQLite database."""
    if not Path(db_path).exists():
        raise FileNotFoundError(f"Database file not found: {db_path}")

    conn = sqlite3.connect(db_path)

    # Read the mgpusim_metrics table
    query = "SELECT Location, What, Value, Unit FROM mgpusim_metrics"
    df = pd.read_sql_query(query, conn)
    conn.close()

    return df


def plot_dram_memory_usage(df):
    """Plot DRAM memory read/write sizes."""
    # Filter DRAM-related metrics
    dram_df = df[df['Location'].str.contains('DRAM', case=False, na=False)]

    # Get read and write sizes
    read_size_df = dram_df[dram_df['What'] == 'read_size']
    write_size_df = dram_df[dram_df['What'] == 'write_size']

    if read_size_df.empty and write_size_df.empty:
        print("No DRAM memory size data found in database.")
        return None

    fig, ax = plt.subplots(figsize=(12, 6))

    locations = sorted(set(read_size_df['Location'].tolist() + write_size_df['Location'].tolist()))
    x = np.arange(len(locations))
    width = 0.35

    read_values = []
    write_values = []

    for loc in locations:
        read_val = read_size_df[read_size_df['Location'] == loc]['Value'].values
        write_val = write_size_df[write_size_df['Location'] == loc]['Value'].values

        read_values.append(read_val[0] if len(read_val) > 0 else 0)
        write_values.append(write_val[0] if len(write_val) > 0 else 0)

    # Convert bytes to MB for better readability
    read_values_mb = [v / (1024 * 1024) for v in read_values]
    write_values_mb = [v / (1024 * 1024) for v in write_values]

    ax.bar(x - width/2, read_values_mb, width, label='Read', color='skyblue')
    ax.bar(x + width/2, write_values_mb, width, label='Write', color='lightcoral')

    ax.set_xlabel('DRAM Component')
    ax.set_ylabel('Data Size (MB)')
    ax.set_title('DRAM Memory Read/Write Sizes')
    ax.set_xticks(x)
    ax.set_xticklabels(locations, rotation=45, ha='right')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    return fig


def plot_dram_transaction_counts(df):
    """Plot DRAM transaction counts."""
    dram_df = df[df['Location'].str.contains('DRAM', case=False, na=False)]

    read_trans_df = dram_df[dram_df['What'] == 'read_trans_count']
    write_trans_df = dram_df[dram_df['What'] == 'write_trans_count']

    if read_trans_df.empty and write_trans_df.empty:
        print("No DRAM transaction count data found in database.")
        return None

    fig, ax = plt.subplots(figsize=(12, 6))

    locations = sorted(set(read_trans_df['Location'].tolist() + write_trans_df['Location'].tolist()))
    x = np.arange(len(locations))
    width = 0.35

    read_counts = []
    write_counts = []

    for loc in locations:
        read_val = read_trans_df[read_trans_df['Location'] == loc]['Value'].values
        write_val = write_trans_df[write_trans_df['Location'] == loc]['Value'].values

        read_counts.append(read_val[0] if len(read_val) > 0 else 0)
        write_counts.append(write_val[0] if len(write_val) > 0 else 0)

    ax.bar(x - width/2, read_counts, width, label='Read Transactions', color='steelblue')
    ax.bar(x + width/2, write_counts, width, label='Write Transactions', color='indianred')

    ax.set_xlabel('DRAM Component')
    ax.set_ylabel('Transaction Count')
    ax.set_title('DRAM Read/Write Transaction Counts')
    ax.set_xticks(x)
    ax.set_xticklabels(locations, rotation=45, ha='right')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    return fig


def plot_dram_latencies(df):
    """Plot DRAM average latencies."""
    dram_df = df[df['Location'].str.contains('DRAM', case=False, na=False)]

    read_lat_df = dram_df[dram_df['What'] == 'read_avg_latency']
    write_lat_df = dram_df[dram_df['What'] == 'write_avg_latency']

    if read_lat_df.empty and write_lat_df.empty:
        print("No DRAM latency data found in database.")
        return None

    fig, ax = plt.subplots(figsize=(12, 6))

    locations = sorted(set(read_lat_df['Location'].tolist() + write_lat_df['Location'].tolist()))
    x = np.arange(len(locations))
    width = 0.35

    read_lats = []
    write_lats = []

    for loc in locations:
        read_val = read_lat_df[read_lat_df['Location'] == loc]['Value'].values
        write_val = write_lat_df[write_lat_df['Location'] == loc]['Value'].values

        read_lats.append(read_val[0] * 1e9 if len(read_val) > 0 else 0)  # Convert to nanoseconds
        write_lats.append(write_val[0] * 1e9 if len(write_val) > 0 else 0)

    ax.bar(x - width/2, read_lats, width, label='Read Latency', color='lightblue')
    ax.bar(x + width/2, write_lats, width, label='Write Latency', color='salmon')

    ax.set_xlabel('DRAM Component')
    ax.set_ylabel('Average Latency (ns)')
    ax.set_title('DRAM Average Read/Write Latencies')
    ax.set_xticks(x)
    ax.set_xticklabels(locations, rotation=45, ha='right')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    return fig


def plot_memory_bandwidth_utilization(df):
    """Plot memory bandwidth utilization (combined read + write)."""
    dram_df = df[df['Location'].str.contains('DRAM', case=False, na=False)]

    read_size_df = dram_df[dram_df['What'] == 'read_size']
    write_size_df = dram_df[dram_df['What'] == 'write_size']

    if read_size_df.empty and write_size_df.empty:
        print("No DRAM size data found in database.")
        return None

    # Get kernel time to calculate bandwidth
    kernel_time_df = df[df['What'] == 'kernel_time']
    if kernel_time_df.empty:
        print("No kernel time data found. Cannot calculate bandwidth.")
        return None

    kernel_time = kernel_time_df.iloc[0]['Value']  # Get total kernel execution time

    fig, ax = plt.subplots(figsize=(12, 6))

    locations = sorted(set(read_size_df['Location'].tolist() + write_size_df['Location'].tolist()))

    bandwidths = []
    total_data = []

    for loc in locations:
        read_val = read_size_df[read_size_df['Location'] == loc]['Value'].values
        write_val = write_size_df[write_size_df['Location'] == loc]['Value'].values

        read_bytes = read_val[0] if len(read_val) > 0 else 0
        write_bytes = write_val[0] if len(write_val) > 0 else 0
        total_bytes = read_bytes + write_bytes

        # Calculate bandwidth in GB/s
        bandwidth_gbps = (total_bytes / kernel_time) / (1024**3)
        bandwidths.append(bandwidth_gbps)
        total_data.append(total_bytes / (1024**2))  # MB

    x = np.arange(len(locations))

    # Create bar plot for bandwidth
    colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(locations)))
    bars = ax.bar(x, bandwidths, color=colors)

    ax.set_xlabel('DRAM Component')
    ax.set_ylabel('Bandwidth (GB/s)')
    ax.set_title(f'Memory Bandwidth Utilization\n(Total Kernel Time: {kernel_time:.4f}s)')
    ax.set_xticks(x)
    ax.set_xticklabels(locations, rotation=45, ha='right')
    ax.grid(axis='y', alpha=0.3)

    # Add value labels on bars
    for i, (bar, bw, data) in enumerate(zip(bars, bandwidths, total_data)):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{bw:.2f} GB/s\n({data:.1f} MB)',
                ha='center', va='bottom', fontsize=8)

    plt.tight_layout()
    return fig


def main():
    if len(sys.argv) < 2:
        print("Usage: python plot_memory_utilization.py <database_file.sqlite3>")
        print("\nTo generate a database file, run a simulation with flags:")
        print("  ./benchmark -timing -report-all")
        print("\nThis will create a file like: akita_sim_<id>.sqlite3")
        sys.exit(1)

    db_path = sys.argv[1]

    try:
        # Load metrics from database
        print(f"Loading metrics from {db_path}...")
        df = load_metrics(db_path)

        print(f"Total metrics loaded: {len(df)}")
        print(f"\nAvailable metric types:")
        for metric_type in sorted(df['What'].unique()):
            count = len(df[df['What'] == metric_type])
            print(f"  - {metric_type}: {count} entries")

        # Generate plots
        print("\nGenerating plots...")

        figures = []

        # Plot 1: Memory sizes
        fig1 = plot_dram_memory_usage(df)
        if fig1:
            figures.append(('memory_sizes', fig1))

        # Plot 2: Transaction counts
        fig2 = plot_dram_transaction_counts(df)
        if fig2:
            figures.append(('transaction_counts', fig2))

        # Plot 3: Latencies
        fig3 = plot_dram_latencies(df)
        if fig3:
            figures.append(('latencies', fig3))

        # Plot 4: Bandwidth utilization
        fig4 = plot_memory_bandwidth_utilization(df)
        if fig4:
            figures.append(('bandwidth', fig4))

        if not figures:
            print("\nNo memory-related metrics found in database.")
            print("Make sure the simulation was run with -report-all flag.")
            return

        # Save figures
        base_name = Path(db_path).stem
        for name, fig in figures:
            output_file = f"{base_name}_{name}.png"
            fig.savefig(output_file, dpi=150, bbox_inches='tight')
            print(f"Saved: {output_file}")

        # Show all plots
        print("\nDisplaying plots...")
        plt.show()

    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
