#!/usr/bin/env python3
"""
Plot memory allocation over time from MGPUSim trace.

Usage:
    python plot_memory_allocation.py [input_file.csv] [--output output.png]

If no input file is specified, it defaults to 'memory_allocation.csv'.
"""

import argparse
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


def plot_memory_allocation(input_file, output_file=None, show_plot=True):
    """
    Plot memory allocation over time from CSV file.

    Args:
        input_file: Path to the CSV file generated by MGPUSim
        output_file: Optional output file path for saving the plot
        show_plot: Whether to display the plot interactively
    """
    try:
        # Read the CSV file
        df = pd.read_csv(input_file)

        # Check if file is empty
        if df.empty:
            print(f"Warning: {input_file} is empty or contains no data.")
            return

        # Get unique devices
        devices = df['DeviceName'].unique()
        num_devices = len(devices)

        if num_devices == 0:
            print("No devices found in the trace file.")
            return

        # Create subplots: 2 rows for each device
        # Row 1: Allocated memory in MB/GB
        # Row 2: Utilization percentage
        fig, axes = plt.subplots(2, 1, figsize=(14, 10))

        # Colors for different devices
        colors = plt.cm.tab10(np.linspace(0, 1, num_devices))

        # Plot 1: Memory allocation over time
        ax1 = axes[0]
        for i, device in enumerate(devices):
            device_data = df[df['DeviceName'] == device]

            # Use GB if total memory is large (> 1024 MB)
            use_gb = device_data['TotalMB'].iloc[0] > 1024

            if use_gb:
                allocated = device_data['AllocatedMB'] / 1024
                total = device_data['TotalMB'] / 1024
                unit = 'GB'
            else:
                allocated = device_data['AllocatedMB']
                total = device_data['TotalMB']
                unit = 'MB'

            # Plot allocated memory
            ax1.plot(device_data['Time(s)'], allocated,
                    label=f'{device} (Allocated)',
                    color=colors[i], linewidth=2)

            # Plot total capacity as horizontal line
            ax1.axhline(y=total.iloc[0],
                       color=colors[i],
                       linestyle='--',
                       alpha=0.5,
                       label=f'{device} (Total: {total.iloc[0]:.2f} {unit})')

        ax1.set_xlabel('Time (seconds)', fontsize=12)
        ax1.set_ylabel(f'Memory ({unit})', fontsize=12)
        ax1.set_title('Memory Allocation Over Time', fontsize=14, fontweight='bold')
        ax1.legend(loc='best', fontsize=9)
        ax1.grid(True, alpha=0.3)

        # Plot 2: Utilization percentage over time
        ax2 = axes[1]
        for i, device in enumerate(devices):
            device_data = df[df['DeviceName'] == device]
            ax2.plot(device_data['Time(s)'], device_data['UtilizationPercent'],
                    label=device, color=colors[i], linewidth=2)

        ax2.set_xlabel('Time (seconds)', fontsize=12)
        ax2.set_ylabel('Utilization (%)', fontsize=12)
        ax2.set_title('Memory Utilization Percentage Over Time', fontsize=14, fontweight='bold')
        ax2.set_ylim(0, 100)
        ax2.legend(loc='best', fontsize=9)
        ax2.grid(True, alpha=0.3)

        # Add overall title
        fig.suptitle('MGPUSim Memory Allocation Analysis',
                    fontsize=16, fontweight='bold', y=0.995)

        plt.tight_layout(rect=[0, 0, 1, 0.99])

        # Save if output file specified
        if output_file:
            plt.savefig(output_file, dpi=300, bbox_inches='tight')
            print(f"Plot saved to {output_file}")

        # Show plot if requested
        if show_plot:
            plt.show()

        # Print summary statistics
        print("\n=== Memory Allocation Summary ===")
        for device in devices:
            device_data = df[df['DeviceName'] == device]
            total_mb = device_data['TotalMB'].iloc[0]
            max_alloc_mb = device_data['AllocatedMB'].max()
            avg_alloc_mb = device_data['AllocatedMB'].mean()
            max_util = device_data['UtilizationPercent'].max()
            avg_util = device_data['UtilizationPercent'].mean()

            print(f"\n{device}:")
            print(f"  Total Memory: {total_mb:.2f} MB ({total_mb/1024:.2f} GB)")
            print(f"  Peak Allocation: {max_alloc_mb:.2f} MB ({max_alloc_mb/1024:.2f} GB)")
            print(f"  Average Allocation: {avg_alloc_mb:.2f} MB ({avg_alloc_mb/1024:.2f} GB)")
            print(f"  Peak Utilization: {max_util:.2f}%")
            print(f"  Average Utilization: {avg_util:.2f}%")

    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.")
        sys.exit(1)
    except pd.errors.EmptyDataError:
        print(f"Error: File '{input_file}' is empty.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading or plotting data: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description='Plot memory allocation over time from MGPUSim trace.'
    )
    parser.add_argument(
        'input_file',
        nargs='?',
        default='memory_allocation.csv',
        help='Input CSV file (default: memory_allocation.csv)'
    )
    parser.add_argument(
        '--output', '-o',
        help='Output file for saving the plot (e.g., plot.png)'
    )
    parser.add_argument(
        '--no-show',
        action='store_true',
        help='Do not display the plot interactively'
    )

    args = parser.parse_args()

    plot_memory_allocation(
        args.input_file,
        output_file=args.output,
        show_plot=not args.no_show
    )


if __name__ == '__main__':
    main()
